schedule: 7000
base_url: "http://127.0.0.1"
port: 3010
verbose: true
jobs:
  - name: 'string-example'
    description: "The description is optional and will only be printed with verbose logging"
    endpoint: '/example/string'
    body: 'You can check string responses'
    status: 200
  - name: 'json-example'
    endpoint: '/example/json'
    body: './responses/posts.json'
    read_file: true
  - name: '404-example'
    endpoint: '/example/404'
    status: 404
